In [ ]:
NumPy (Numerical Python) is the core library for numerical and scientific computing in Python.
Provides fast, memory-efficient operations on large arrays and matrices.
Acts as the base for many libraries like Pandas, SciPy, Scikit-Learn, TensorFlow.

Key Features
    Ndarray (N-Dimensional Array):
    Fast, homogeneous, multidimensional data structure.
    Supports slicing, indexing, reshaping.
Vectorized Operations:
    Perform operations without explicit loops → significant speed improvements.
Broadcasting:
    Automatically expands smaller arrays to match larger ones during operations.
Mathematical Functions:
    Over 500 optimized functions for algebra, statistics, trigonometry, etc.
Random Module:
Random numbers, simulations, probability distributions.

Why NumPy is Fast
    Written in C and optimized for performance.
    Uses contiguous memory blocks → improved CPU cache usage.
    Supports vectorized operations instead of slow Python loops.

In [1]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [2]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
arr.dtype

dtype('int64')

In [64]:
arr.shape
arr.ndim

1

In [5]:
print(arr[0])
print(arr[2:5])

0
[2 3 4]


In [6]:
matrix = np.array([[10,20,30,40], [50,60,70,80],[90,100,110,120]])

In [7]:
matrix

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [65]:
matrix.shape
matrix.ndim

2

In [13]:
matrix[: ,2:]

array([[ 30,  40],
       [ 70,  80],
       [110, 120]])

In [16]:
arr = np.linspace(1,100 ,10)
arr

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [66]:
np.ones((10,5,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1.,

In [26]:
np.eye(10,k=3)

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [27]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

print(arr.shape)  
print(arr.ndim)   
print(arr.size)   


(2, 3)
2
6


In [27]:
#Indexing & Slicing
a= np.array([10, 20, 30, 40, 50])

print(a[0])     
print(a[-1])    
print(a[1:4])   
print(a[:3])    
print(a[::-1])  

10
50
[20 30 40]
[10 20 30]
[50 40 30 20 10]


In [28]:
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(b[0, 1])       
print(b[1:, :2])    
print(b[:, 1])        


2
[[4 5]
 [7 8]]
[2 5 8]


In [ ]:
# vectorization means:
# Writing operations so they work on whole arrays at once, instead of looping through elements in Python.

In [29]:
#with out vectorization
numbers = [1, 2, 3, 4]
squared = []

for x in numbers:
    squared.append(x ** 2)

print(squared)  


[1, 4, 9, 16]


In [30]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [31]:
#Broadcasting is NumPy’s ability to perform element-wise operations on arrays of different 
# shapes by automatically stretching one array to match the other.

In [31]:
import numpy as np

a = np.array([1, 2, 3])
b = 5

print(a + b)


[6 7 8]


In [32]:
#adding rows to matrix
A = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

print(A + b)


[[11 22 33]
 [14 25 36]]


In [33]:
#adding columns to matrix
A = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[10],
              [20]])

print(A + b)


[[11 12 13]
 [24 25 26]]


In [36]:
arr = np.array([1, 4, 9, 16])

print(np.sqrt(arr))
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.pi)
print(np.exp(arr))

print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))


[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[0.         0.60205999 0.95424251 1.20411998]
[0.       2.       3.169925 4.      ]
3.141592653589793
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
7.5
6.5
5.678908345800274
30
16
1


In [38]:
arr = np.arange(12)
print(arr)
print(arr.reshape(3, 4))
print(arr.reshape(2, 2, 3))
print(arr.flatten())


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [39]:
#stacking
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.hstack((a, b)))    # Horizontal
print(np.vstack((a, b)))    # Vertical
print(np.concatenate((a, b), axis=1))


[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [42]:
#boolean indexing
arr = np.array([10, 20, 30, 40, 50])
print(arr >25)
print(arr[arr > 25])       
print(arr[arr % 20 == 0])   


[False False  True  True  True]
[30 40 50]
[20 40]


In [70]:
#random module
print(np.random.rand(3))       # random floats
print(np.random.randint(1, 10, 5))
print(np.random.randn(10,10))    # normal distribution


[0.4071833  0.069167   0.69742877]
[4 3 4 8 8]
[[-1.38282715e-01 -2.12492027e+00 -1.03001883e+00 -5.17451865e-01
  -1.41800012e-01 -1.27648021e+00  1.48151328e+00  1.65927664e+00
   1.39611962e-04  1.50583836e+00]
 [ 1.04520923e-01 -2.36043151e-01  8.19435034e-01  4.02856439e-01
  -1.43824188e+00  2.71248834e-01 -6.90603124e-01 -6.81532976e-01
  -1.51223065e+00  2.19689103e+00]
 [ 1.04117502e+00 -3.32360282e-02  6.56412810e-02  2.65785722e-01
   1.15184215e+00  1.38042881e-01 -1.47805531e-01  1.68382745e+00
   9.71832126e-01  1.60767401e+00]
 [-2.57127738e-01  1.80981769e+00  8.92348499e-01 -9.65761274e-02
  -3.77157018e-01 -5.05297741e-01 -1.36267113e+00  1.13312703e+00
  -7.00689758e-01 -1.76834790e+00]
 [ 3.40417282e-01  7.29241691e-01 -1.08835382e+00 -2.87777873e+00
  -6.61477691e-01  7.05928389e-01 -3.58597842e-01  7.31982454e-01
  -3.63665328e-02  5.88914219e-01]
 [-7.79634808e-01  4.76336690e-01  8.33880115e-01  1.31379269e+00
  -6.01708598e-01 -5.47163800e-01  6.09650793e-01  7

In [40]:
#leanier algibra
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[10, 20],
              [30, 40]])

print(np.dot(A, B))           # Matrix multiplication
print(np.linalg.inv(A))       # Inverse
print(np.linalg.det(A))       # Determinant
print(np.linalg.eig(A))       # Eigenvalues, eigenvectors


[[ 70 100]
 [150 220]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [71]:
#reading and writting
arr = np.array([1, 2, 3])

np.save('array.npy', arr)         # Save
loaded = np.load('array.npy')     # Load

np.savetxt('c:/data/data.txt', arr)
print(np.loadtxt('c:/data/data.txt'))


[1. 2. 3.]


In [72]:
pwd

'C:\\Users\\Babjee reddy'